KasperZutterman/Second-Brain

README.md

Corrected link to Anshul's Twitter

Twitter Link Corrected

---

README.md

- Richard Haines
- Paul Scanlon

add other gardens

---

README.md

Hey, 
Thanks for putting this together! Just wanted to add mine to the list as well.
Cheers
Azer

Add Azer's public & digital notebook

---

README.md

Added my personal digital garden to the list with notes on coding, note taking, personal knowledge management and other random thoughts.

Added my Second Brain

---

README.md

Hi there! I just wanted to add my own Digital Garden to this living list, I hope that's alright! I'm happy the movement is growing!

add my Digital Garden to the list

---

README.md

Also fixed an url - didn't have the http part.

Added my Zettelkasten to the list

---

README.md

Collection of my personal notes. 
My main criticism of knowledge bases is opacity. I try to adress it with a clear readme that quickly shows what's "inside". Some bits might be interesting to other folks.

Added my digital garden

---

README.md

This adds [notes.arne.me](https://notes.arne.me) to the list.

Add Arnes notes

---

README.md

Some unmissable digital gardens with +500 notes around multiple subjects gathered from the Obsidian.md community.

Add digital gardens from the Obsidian.md community 

---

README.md
test_urls.sh

Thought I'd add my site to the mix of second brains, since it's been heavily inspired by others on this list.
To help with maintenance I added a shell script to read every url in this list and verify that it's reachable. Double-check any url in your browser in the off-chance that site's host doesn't allow HEAD requests, but it should make it easy to find broken links.

Add Alex and Test Script

---

README.md

Updated my notes website link and twitter profile

Updated my notes website link and twitter profile

---

README.md

I added [my digital garden](https://tommi.space/jam).

Added tommi.space

---

README.md

Obsidian Published Vault: https://publish.obsidian.md/kaas-published 
GitHub Pages MkDocs Customized Site: https://kaas.jimbrig.com
GitHub Repository (separate branches for separate sites): https://github.com/jimbrig/kaas
Thanks!

Update README with KaaS Vault by Jimmy Briggs

---

README.md

Added https://notes.whoibrar.com in the ReadMe File

added a site notes.whoibrar.com

---

README.md

Wanted to add my digital garden to your collection! Thanks.

Add Will Bamberg's digital garden to list

---

README.md

I added my (new) digital garden to the list.

adds Marcus Hughes

---

README.md

The URL for his site points to spam now.

remove Cristian Rojas

---

README.md

This adds a link to my Forest, a public Zettelkasten

Add my public zettelkasten ("forest")

---

README.md

I found two awesome chinese digital gardens. These two websites both use [quartz](https://github.com/jackyzha0/quartz) to generate the website, which I also thought was a great tool!
kudos to @jackyzha0 for creating both great website and tool👍

Add links for Jack Zhao and DongDong Chen's digital garden website link.

---

README.md

Hi! My site is primarily a digital garden! Thank you for compiling such an amazing list!

add foreverlikethis

---

README.md

Please consider adding my digital garden to your collection! Thanks.

add link to Serge Kazakov's digital garden

---

README.md

I recently changed my github username/domain name,
thought I would PR a fix

update: update domain name for my website

---

README.md

Love the list. I've been wading through it and finding so many great sites, so I figured I'd throw mine into the arena.

Add Declan Chidlow's Vale.Rocks
